[SERVICE]
    Flush         5
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224

[FILTER]
    Name              parser
    Match             waf.*
    Key_Name          log
    Parser            modsec_json
    Reserve_Data      On

[OUTPUT]
    Name                es
    Match               waf.*
    Host                opensearch
    Port                9200
    Index               modsec-logs
    Suppress_Type_Name  On
    Retry_Limit         5
